// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/Falokut/movies_service/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockMoviesRepositoryManager is a mock of MoviesRepositoryManager interface.
type MockMoviesRepositoryManager struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesRepositoryManagerMockRecorder
}

// MockMoviesRepositoryManagerMockRecorder is the mock recorder for MockMoviesRepositoryManager.
type MockMoviesRepositoryManagerMockRecorder struct {
	mock *MockMoviesRepositoryManager
}

// NewMockMoviesRepositoryManager creates a new mock instance.
func NewMockMoviesRepositoryManager(ctrl *gomock.Controller) *MockMoviesRepositoryManager {
	mock := &MockMoviesRepositoryManager{ctrl: ctrl}
	mock.recorder = &MockMoviesRepositoryManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesRepositoryManager) EXPECT() *MockMoviesRepositoryManagerMockRecorder {
	return m.recorder
}

// GetMovie mocks base method.
func (m *MockMoviesRepositoryManager) GetMovie(ctx context.Context, movieId string) (repository.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, movieId)
	ret0, _ := ret[0].(repository.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetMovie(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetMovie), ctx, movieId)
}

// GetMovies mocks base method.
func (m *MockMoviesRepositoryManager) GetMovies(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32) ([]repository.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovies", ctx, Filter, limit, offset)
	ret0, _ := ret[0].([]repository.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovies indicates an expected call of GetMovies.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetMovies(ctx, Filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovies", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetMovies), ctx, Filter, limit, offset)
}

// MockMoviesRepository is a mock of MoviesRepository interface.
type MockMoviesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesRepositoryMockRecorder
}

// MockMoviesRepositoryMockRecorder is the mock recorder for MockMoviesRepository.
type MockMoviesRepositoryMockRecorder struct {
	mock *MockMoviesRepository
}

// NewMockMoviesRepository creates a new mock instance.
func NewMockMoviesRepository(ctrl *gomock.Controller) *MockMoviesRepository {
	mock := &MockMoviesRepository{ctrl: ctrl}
	mock.recorder = &MockMoviesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesRepository) EXPECT() *MockMoviesRepositoryMockRecorder {
	return m.recorder
}

// GetMovie mocks base method.
func (m *MockMoviesRepository) GetMovie(ctx context.Context, movieId string) (repository.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, movieId)
	ret0, _ := ret[0].(repository.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockMoviesRepositoryMockRecorder) GetMovie(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockMoviesRepository)(nil).GetMovie), ctx, movieId)
}

// GetMovies mocks base method.
func (m *MockMoviesRepository) GetMovies(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovies", ctx, Filter, limit, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovies indicates an expected call of GetMovies.
func (mr *MockMoviesRepositoryMockRecorder) GetMovies(ctx, Filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovies", reflect.TypeOf((*MockMoviesRepository)(nil).GetMovies), ctx, Filter, limit, offset)
}

// MockMoviesCache is a mock of MoviesCache interface.
type MockMoviesCache struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesCacheMockRecorder
}

// MockMoviesCacheMockRecorder is the mock recorder for MockMoviesCache.
type MockMoviesCacheMockRecorder struct {
	mock *MockMoviesCache
}

// NewMockMoviesCache creates a new mock instance.
func NewMockMoviesCache(ctrl *gomock.Controller) *MockMoviesCache {
	mock := &MockMoviesCache{ctrl: ctrl}
	mock.recorder = &MockMoviesCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesCache) EXPECT() *MockMoviesCacheMockRecorder {
	return m.recorder
}

// CacheFilteredRequest mocks base method.
func (m *MockMoviesCache) CacheFilteredRequest(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32, moviesIDs []string, TTL time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheFilteredRequest", ctx, Filter, limit, offset, moviesIDs, TTL)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheFilteredRequest indicates an expected call of CacheFilteredRequest.
func (mr *MockMoviesCacheMockRecorder) CacheFilteredRequest(ctx, Filter, limit, offset, moviesIDs, TTL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheFilteredRequest", reflect.TypeOf((*MockMoviesCache)(nil).CacheFilteredRequest), ctx, Filter, limit, offset, moviesIDs, TTL)
}

// CacheMovies mocks base method.
func (m *MockMoviesCache) CacheMovies(ctx context.Context, movies []repository.Movie, TTL time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheMovies", ctx, movies, TTL)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheMovies indicates an expected call of CacheMovies.
func (mr *MockMoviesCacheMockRecorder) CacheMovies(ctx, movies, TTL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheMovies", reflect.TypeOf((*MockMoviesCache)(nil).CacheMovies), ctx, movies, TTL)
}

// GetMovie mocks base method.
func (m *MockMoviesCache) GetMovie(ctx context.Context, movieId string) (repository.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, movieId)
	ret0, _ := ret[0].(repository.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockMoviesCacheMockRecorder) GetMovie(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockMoviesCache)(nil).GetMovie), ctx, movieId)
}

// GetMovies mocks base method.
func (m *MockMoviesCache) GetMovies(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovies", ctx, Filter, limit, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovies indicates an expected call of GetMovies.
func (mr *MockMoviesCacheMockRecorder) GetMovies(ctx, Filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovies", reflect.TypeOf((*MockMoviesCache)(nil).GetMovies), ctx, Filter, limit, offset)
}
