// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/Falokut/movies_service/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockMoviesRepositoryManager is a mock of MoviesRepositoryManager interface.
type MockMoviesRepositoryManager struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesRepositoryManagerMockRecorder
}

// MockMoviesRepositoryManagerMockRecorder is the mock recorder for MockMoviesRepositoryManager.
type MockMoviesRepositoryManagerMockRecorder struct {
	mock *MockMoviesRepositoryManager
}

// NewMockMoviesRepositoryManager creates a new mock instance.
func NewMockMoviesRepositoryManager(ctrl *gomock.Controller) *MockMoviesRepositoryManager {
	mock := &MockMoviesRepositoryManager{ctrl: ctrl}
	mock.recorder = &MockMoviesRepositoryManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesRepositoryManager) EXPECT() *MockMoviesRepositoryManagerMockRecorder {
	return m.recorder
}

// GetAgeRatings mocks base method.
func (m *MockMoviesRepositoryManager) GetAgeRatings(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgeRatings", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgeRatings indicates an expected call of GetAgeRatings.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetAgeRatings(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgeRatings", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetAgeRatings), ctx)
}

// GetAllCountries mocks base method.
func (m *MockMoviesRepositoryManager) GetAllCountries(ctx context.Context) ([]repository.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCountries", ctx)
	ret0, _ := ret[0].([]repository.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCountries indicates an expected call of GetAllCountries.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetAllCountries(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCountries", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetAllCountries), ctx)
}

// GetAllGenres mocks base method.
func (m *MockMoviesRepositoryManager) GetAllGenres(ctx context.Context) ([]repository.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGenres", ctx)
	ret0, _ := ret[0].([]repository.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGenres indicates an expected call of GetAllGenres.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetAllGenres(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGenres", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetAllGenres), ctx)
}

// GetCountries mocks base method.
func (m *MockMoviesRepositoryManager) GetCountries(ctx context.Context, movieId int32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountries", ctx, movieId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountries indicates an expected call of GetCountries.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetCountries(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountries", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetCountries), ctx, movieId)
}

// GetGenres mocks base method.
func (m *MockMoviesRepositoryManager) GetGenres(ctx context.Context, movieId int32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenres", ctx, movieId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenres indicates an expected call of GetGenres.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetGenres(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenres", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetGenres), ctx, movieId)
}

// GetMovie mocks base method.
func (m *MockMoviesRepositoryManager) GetMovie(ctx context.Context, movieId int32) (repository.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, movieId)
	ret0, _ := ret[0].(repository.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetMovie(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetMovie), ctx, movieId)
}

// GetMoviePreview mocks base method.
func (m *MockMoviesRepositoryManager) GetMoviePreview(ctx context.Context, movieId int32) (repository.MoviePreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoviePreview", ctx, movieId)
	ret0, _ := ret[0].(repository.MoviePreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMoviePreview indicates an expected call of GetMoviePreview.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetMoviePreview(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviePreview", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetMoviePreview), ctx, movieId)
}

// GetMoviesPreview mocks base method.
func (m *MockMoviesRepositoryManager) GetMoviesPreview(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32) ([]repository.MoviePreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoviesPreview", ctx, Filter, limit, offset)
	ret0, _ := ret[0].([]repository.MoviePreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMoviesPreview indicates an expected call of GetMoviesPreview.
func (mr *MockMoviesRepositoryManagerMockRecorder) GetMoviesPreview(ctx, Filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviesPreview", reflect.TypeOf((*MockMoviesRepositoryManager)(nil).GetMoviesPreview), ctx, Filter, limit, offset)
}

// MockMoviesRepository is a mock of MoviesRepository interface.
type MockMoviesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesRepositoryMockRecorder
}

// MockMoviesRepositoryMockRecorder is the mock recorder for MockMoviesRepository.
type MockMoviesRepositoryMockRecorder struct {
	mock *MockMoviesRepository
}

// NewMockMoviesRepository creates a new mock instance.
func NewMockMoviesRepository(ctrl *gomock.Controller) *MockMoviesRepository {
	mock := &MockMoviesRepository{ctrl: ctrl}
	mock.recorder = &MockMoviesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesRepository) EXPECT() *MockMoviesRepositoryMockRecorder {
	return m.recorder
}

// GetMovie mocks base method.
func (m *MockMoviesRepository) GetMovie(ctx context.Context, movieId int32) (repository.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, movieId)
	ret0, _ := ret[0].(repository.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockMoviesRepositoryMockRecorder) GetMovie(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockMoviesRepository)(nil).GetMovie), ctx, movieId)
}

// MockAgeRatingRepository is a mock of AgeRatingRepository interface.
type MockAgeRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAgeRatingRepositoryMockRecorder
}

// MockAgeRatingRepositoryMockRecorder is the mock recorder for MockAgeRatingRepository.
type MockAgeRatingRepositoryMockRecorder struct {
	mock *MockAgeRatingRepository
}

// NewMockAgeRatingRepository creates a new mock instance.
func NewMockAgeRatingRepository(ctrl *gomock.Controller) *MockAgeRatingRepository {
	mock := &MockAgeRatingRepository{ctrl: ctrl}
	mock.recorder = &MockAgeRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgeRatingRepository) EXPECT() *MockAgeRatingRepositoryMockRecorder {
	return m.recorder
}

// GetAgeRatings mocks base method.
func (m *MockAgeRatingRepository) GetAgeRatings(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgeRatings", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgeRatings indicates an expected call of GetAgeRatings.
func (mr *MockAgeRatingRepositoryMockRecorder) GetAgeRatings(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgeRatings", reflect.TypeOf((*MockAgeRatingRepository)(nil).GetAgeRatings), ctx)
}

// MockMoviesPreviewRepository is a mock of MoviesPreviewRepository interface.
type MockMoviesPreviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesPreviewRepositoryMockRecorder
}

// MockMoviesPreviewRepositoryMockRecorder is the mock recorder for MockMoviesPreviewRepository.
type MockMoviesPreviewRepositoryMockRecorder struct {
	mock *MockMoviesPreviewRepository
}

// NewMockMoviesPreviewRepository creates a new mock instance.
func NewMockMoviesPreviewRepository(ctrl *gomock.Controller) *MockMoviesPreviewRepository {
	mock := &MockMoviesPreviewRepository{ctrl: ctrl}
	mock.recorder = &MockMoviesPreviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesPreviewRepository) EXPECT() *MockMoviesPreviewRepositoryMockRecorder {
	return m.recorder
}

// GetMoviePreview mocks base method.
func (m *MockMoviesPreviewRepository) GetMoviePreview(ctx context.Context, movieId int32) (repository.MoviePreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoviePreview", ctx, movieId)
	ret0, _ := ret[0].(repository.MoviePreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMoviePreview indicates an expected call of GetMoviePreview.
func (mr *MockMoviesPreviewRepositoryMockRecorder) GetMoviePreview(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviePreview", reflect.TypeOf((*MockMoviesPreviewRepository)(nil).GetMoviePreview), ctx, movieId)
}

// GetMoviesPreview mocks base method.
func (m *MockMoviesPreviewRepository) GetMoviesPreview(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoviesPreview", ctx, Filter, limit, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMoviesPreview indicates an expected call of GetMoviesPreview.
func (mr *MockMoviesPreviewRepositoryMockRecorder) GetMoviesPreview(ctx, Filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviesPreview", reflect.TypeOf((*MockMoviesPreviewRepository)(nil).GetMoviesPreview), ctx, Filter, limit, offset)
}

// MockMoviesCache is a mock of MoviesCache interface.
type MockMoviesCache struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesCacheMockRecorder
}

// MockMoviesCacheMockRecorder is the mock recorder for MockMoviesCache.
type MockMoviesCacheMockRecorder struct {
	mock *MockMoviesCache
}

// NewMockMoviesCache creates a new mock instance.
func NewMockMoviesCache(ctrl *gomock.Controller) *MockMoviesCache {
	mock := &MockMoviesCache{ctrl: ctrl}
	mock.recorder = &MockMoviesCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesCache) EXPECT() *MockMoviesCacheMockRecorder {
	return m.recorder
}

// CacheMovies mocks base method.
func (m *MockMoviesCache) CacheMovies(ctx context.Context, movies []repository.Movie, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheMovies", ctx, movies, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheMovies indicates an expected call of CacheMovies.
func (mr *MockMoviesCacheMockRecorder) CacheMovies(ctx, movies, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheMovies", reflect.TypeOf((*MockMoviesCache)(nil).CacheMovies), ctx, movies, ttl)
}

// GetMovie mocks base method.
func (m *MockMoviesCache) GetMovie(ctx context.Context, movieId int32) (repository.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, movieId)
	ret0, _ := ret[0].(repository.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockMoviesCacheMockRecorder) GetMovie(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockMoviesCache)(nil).GetMovie), ctx, movieId)
}

// MockMoviesPreviewCache is a mock of MoviesPreviewCache interface.
type MockMoviesPreviewCache struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesPreviewCacheMockRecorder
}

// MockMoviesPreviewCacheMockRecorder is the mock recorder for MockMoviesPreviewCache.
type MockMoviesPreviewCacheMockRecorder struct {
	mock *MockMoviesPreviewCache
}

// NewMockMoviesPreviewCache creates a new mock instance.
func NewMockMoviesPreviewCache(ctrl *gomock.Controller) *MockMoviesPreviewCache {
	mock := &MockMoviesPreviewCache{ctrl: ctrl}
	mock.recorder = &MockMoviesPreviewCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesPreviewCache) EXPECT() *MockMoviesPreviewCacheMockRecorder {
	return m.recorder
}

// CacheFilteredRequest mocks base method.
func (m *MockMoviesPreviewCache) CacheFilteredRequest(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32, moviesIDs []string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheFilteredRequest", ctx, Filter, limit, offset, moviesIDs, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheFilteredRequest indicates an expected call of CacheFilteredRequest.
func (mr *MockMoviesPreviewCacheMockRecorder) CacheFilteredRequest(ctx, Filter, limit, offset, moviesIDs, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheFilteredRequest", reflect.TypeOf((*MockMoviesPreviewCache)(nil).CacheFilteredRequest), ctx, Filter, limit, offset, moviesIDs, ttl)
}

// CacheMovies mocks base method.
func (m *MockMoviesPreviewCache) CacheMovies(ctx context.Context, movies []repository.MoviePreview, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheMovies", ctx, movies, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheMovies indicates an expected call of CacheMovies.
func (mr *MockMoviesPreviewCacheMockRecorder) CacheMovies(ctx, movies, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheMovies", reflect.TypeOf((*MockMoviesPreviewCache)(nil).CacheMovies), ctx, movies, ttl)
}

// GetMovie mocks base method.
func (m *MockMoviesPreviewCache) GetMovie(ctx context.Context, movieId int32) (repository.MoviePreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, movieId)
	ret0, _ := ret[0].(repository.MoviePreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockMoviesPreviewCacheMockRecorder) GetMovie(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockMoviesPreviewCache)(nil).GetMovie), ctx, movieId)
}

// GetMovies mocks base method.
func (m *MockMoviesPreviewCache) GetMovies(ctx context.Context, Filter repository.MoviesFilter, limit, offset uint32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovies", ctx, Filter, limit, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovies indicates an expected call of GetMovies.
func (mr *MockMoviesPreviewCacheMockRecorder) GetMovies(ctx, Filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovies", reflect.TypeOf((*MockMoviesPreviewCache)(nil).GetMovies), ctx, Filter, limit, offset)
}

// MockGenresRepository is a mock of GenresRepository interface.
type MockGenresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGenresRepositoryMockRecorder
}

// MockGenresRepositoryMockRecorder is the mock recorder for MockGenresRepository.
type MockGenresRepositoryMockRecorder struct {
	mock *MockGenresRepository
}

// NewMockGenresRepository creates a new mock instance.
func NewMockGenresRepository(ctrl *gomock.Controller) *MockGenresRepository {
	mock := &MockGenresRepository{ctrl: ctrl}
	mock.recorder = &MockGenresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenresRepository) EXPECT() *MockGenresRepositoryMockRecorder {
	return m.recorder
}

// GetAllGenres mocks base method.
func (m *MockGenresRepository) GetAllGenres(ctx context.Context) ([]repository.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGenres", ctx)
	ret0, _ := ret[0].([]repository.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGenres indicates an expected call of GetAllGenres.
func (mr *MockGenresRepositoryMockRecorder) GetAllGenres(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGenres", reflect.TypeOf((*MockGenresRepository)(nil).GetAllGenres), ctx)
}

// GetGenres mocks base method.
func (m *MockGenresRepository) GetGenres(ctx context.Context, movieId int32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenres", ctx, movieId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenres indicates an expected call of GetGenres.
func (mr *MockGenresRepositoryMockRecorder) GetGenres(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenres", reflect.TypeOf((*MockGenresRepository)(nil).GetGenres), ctx, movieId)
}

// MockCountryRepository is a mock of CountryRepository interface.
type MockCountryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCountryRepositoryMockRecorder
}

// MockCountryRepositoryMockRecorder is the mock recorder for MockCountryRepository.
type MockCountryRepositoryMockRecorder struct {
	mock *MockCountryRepository
}

// NewMockCountryRepository creates a new mock instance.
func NewMockCountryRepository(ctrl *gomock.Controller) *MockCountryRepository {
	mock := &MockCountryRepository{ctrl: ctrl}
	mock.recorder = &MockCountryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCountryRepository) EXPECT() *MockCountryRepositoryMockRecorder {
	return m.recorder
}

// GetAllCountries mocks base method.
func (m *MockCountryRepository) GetAllCountries(ctx context.Context) ([]repository.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCountries", ctx)
	ret0, _ := ret[0].([]repository.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCountries indicates an expected call of GetAllCountries.
func (mr *MockCountryRepositoryMockRecorder) GetAllCountries(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCountries", reflect.TypeOf((*MockCountryRepository)(nil).GetAllCountries), ctx)
}

// GetCountries mocks base method.
func (m *MockCountryRepository) GetCountries(ctx context.Context, movieId int32) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountries", ctx, movieId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountries indicates an expected call of GetCountries.
func (mr *MockCountryRepositoryMockRecorder) GetCountries(ctx, movieId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountries", reflect.TypeOf((*MockCountryRepository)(nil).GetCountries), ctx, movieId)
}
