// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockImagesService is a mock of ImagesService interface.
type MockImagesService struct {
	ctrl     *gomock.Controller
	recorder *MockImagesServiceMockRecorder
}

// MockImagesServiceMockRecorder is the mock recorder for MockImagesService.
type MockImagesServiceMockRecorder struct {
	mock *MockImagesService
}

// NewMockImagesService creates a new mock instance.
func NewMockImagesService(ctrl *gomock.Controller) *MockImagesService {
	mock := &MockImagesService{ctrl: ctrl}
	mock.recorder = &MockImagesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImagesService) EXPECT() *MockImagesServiceMockRecorder {
	return m.recorder
}

// GetMoviePosterURL mocks base method.
func (m *MockImagesService) GetMoviePosterURL(ctx context.Context, PictureID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoviePosterURL", ctx, PictureID)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMoviePosterURL indicates an expected call of GetMoviePosterURL.
func (mr *MockImagesServiceMockRecorder) GetMoviePosterURL(ctx, PictureID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviePosterURL", reflect.TypeOf((*MockImagesService)(nil).GetMoviePosterURL), ctx, PictureID)
}
